apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 463516543158.dkr.ecr.us-east-1.amazonaws.com/clo835-assignment-1-db:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE
          value: "employees"